name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Add Android Platform support, Change App Name & Fix Kotlin Stdlib conflicts
        run: |
          cd invoice_flutter
          flutter create --platforms=android --org com.velmurugan .
          # Change App Name in AndroidManifest
          sed -i 's/android:label="invoice_flutter"/android:label="Vel Invoice bill"/g' android/app/src/main/AndroidManifest.xml
          # Fix duplicate Kotlin Stdlib classes conflict
          echo -e "\nconfigurations.all {\n    resolutionStrategy {\n        eachDependency { details ->\n            if (details.requested.group == 'org.jetbrains.kotlin') {\n                details.useVersion '1.8.10'\n            }\n        }\n    }\n}" >> android/app/build.gradle

      - name: Install Dependencies
        run: |
          cd invoice_flutter
          flutter pub get

      - name: Generate App Launcher Icons
        run: |
          cd invoice_flutter
          flutter pub run flutter_launcher_icons

      - name: Build Release APK
        run: |
          cd invoice_flutter
          flutter build apk --release --no-shrink

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gst-invoice-app-apk
          path: invoice_flutter/build/app/outputs/flutter-apk/app-release.apk
